In [2]:
import numpy as np

my_array = np.arange(1000000) #numpy에게 백만개짜리의 리스트 만들어달라고 요청
my_list = list(range(1000000)) #리스트에 저장

In [4]:
# 리스트 내부 모든 숫자에 2를 곱하기

%timeit my_list2 = [i*2 for i in my_list]
%timeit my_array2 = my_array * 2

112 ms ± 6.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.18 ms ± 198 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a)
print(data)

# 리스트 내부에 소수
# -> array 내부의 모든 데이터를 일괄적으로 소수로 바꿔줌
# -> 나중 계산 편하게 하기 위해서

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [9]:
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [ ]:
# 0차원: 스칼라(scala), 1차원: 벡터(vector), 2차원: 행렬(matrix), 3차원: 텐서(tenser)

In [10]:
print(data.shape)

(2, 3)


In [11]:
print(data.dtype)

float64


### ndarray 생성하기

In [15]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)

In [16]:
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [18]:
print(arr1.ndim)
print(arr2.ndim)
#차원수

1
2


In [19]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [22]:
# 데이터 없이 미리 규격을 만들 때

# 1차원
print(np.zeros(10))
print([0] * 10) # 이 코드와 같음

# 2차원
print(np.zeros((5,5)))

print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [23]:
# 0부터 9까지 순서대로 배열 생성
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(arr1.dtype)
print(arr2.dtype)


int64
int64


In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)


float64
int32


In [28]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)

float_arr1 = arr1.astype(np.float64) # astype() 내장 함수로 형변환 시켜줌
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [29]:
arr2 = np.array([1.1, 2.2, 3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


### 산술 연산

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [32]:
print(arr * arr) # 행렬에서의 곱셈과는 다름

[[ 1  4  9]
 [16 25 36]]


In [33]:
print(arr + arr)

[[ 2  4  6]
 [ 8 10 12]]


In [35]:
print(1 / arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [36]:
print(arr ** 3)

[[  1   8  27]
 [ 64 125 216]]


In [39]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


### 색인(인덱싱)과 슬라이싱

In [41]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
print(arr[7])

7


In [45]:
print(arr[2:5])

[2 3 4]


In [46]:
arr[2:5] = 10

In [47]:
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [48]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# 데이터 5에 접근하고 싶다면?
print(arr[1][1]) # 리스트에서 사용하던 방법임. 이것도 동작하긴 함. 하지만 더 높은 차원에서 접근할 땐 불편함
# 편의 기능
print(arr[1, 1]) # 대괄호를 하나만 써도 가능

[[1 2 3]
 [4 5 6]]
5
5


In [53]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
          [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
          [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [54]:
print(arr3d.shape)

(3, 3, 3)


In [59]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [62]:
arr3d[:1, 1:, 2:]

array([[[6],
        [9]]])

In [63]:
arr3d[0, 1:, 2:]

array([[6],
       [9]])

In [64]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


In [66]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

# data에서 hong의 데이터만 고르고 싶다면?
# 먼저 불리언 데이터를 만들어낼 것임
# == 연산이 가능

names == 'hong'
# name 데이터 중 hong과 같은지 확인하기
# 연산 결과가 True 혹은 False로 나옴

array([ True, False,  True, False])

In [70]:
#data[[True, False, True, False]]
print(data[names == 'hong'])
# -> True 위치에 있는 데이터만 분리시켜줌
# 특정 조건에 맞는 데이터 고를 때 이 방법 사용함

[['math' '60']
 ['eng' '70']]


In [71]:
# 점수만 따로 보고 싶다면?
print(data[names == 'hong', 1]) # 인덱스 접근 -> 1차원 출력
print(data[names == 'hong', :1]) # 슬라이싱 접근 -> 2차원 출력


['60' '70']
[['math']
 ['eng']]


In [72]:
print(names != 'hong')

[False  True False  True]


In [73]:
print(~(names == 'hong'))

[False  True False  True]


In [74]:
cond = names == 'kim' # 결과를 condition 변수에 저장함
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

### 팬시 색인(fancy indexing)

In [76]:
arr = np.zeros((8, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [77]:
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [78]:
# 팬시 인덱싱은 특정해서 가져올 때 사용함

In [80]:
arr[[4, 3, 0, 5]]
# 4번째 행, 3번째 행... 을 직접 골라서 가져옴
# 대괄호 내부에 대괄호 한 번 더 작성하는 것이 문법
# 원하는 행 선택
# 순서도 내가 지정한 순서대로 출력해줌

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [82]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [86]:
arr = np.arange(32).reshape(8, 4) # reshape: 내가 가진 행렬의 가로세로 shape 수정할 때 시용함
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [87]:
arr[[1, 5]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [88]:
arr[[1, 5], [2, 3]] # 1, 2 데이터와 5, 3의 데이터가 출력됨

array([ 6, 23])

In [92]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

### 배열 전치

In [94]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [95]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [96]:
arr @ arr.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [100]:
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


### numpy 함수

In [101]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[ 1.05250711 -0.28198589 -0.68727893]
 [-0.81193952  0.79404768 -0.00355644]
 [-0.82904624 -0.83320637 -1.46696501]]


In [104]:
arr1 = np.sqrt(samples) #루트
# nan (not a number): 숫자가 아닙니다(none과 비슷한 개념, 주로 음수일 때)
# nan -> '결측치'라고 부르게 될 것
print(arr1)

[[1.02591769        nan        nan]
 [       nan 0.89109353        nan]
 [       nan        nan        nan]]


C:\Users\1-09\AppData\Local\Temp\ipykernel_10908\806083388.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples) #루트


In [105]:
arr2 = np.abs(samples)
print(arr2)

[[1.05250711 0.28198589 0.68727893]
 [0.81193952 0.79404768 0.00355644]
 [0.82904624 0.83320637 1.46696501]]


In [106]:
np.isnan(arr1)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])